### PR TITLE
Support multi-language translation

### PR DESCRIPTION
**Pull request by neighbor-bear**
Add corresponding text to String to facilitate multi-language translation

### CODE REVIEW

**Comment by twaik** [comment]
Multi-language translation is not going to be implemented.

**Comment by Biswa96** [comment]
> Multi-language translation is not going to be implemented.

An explanation of the rationale behind this decision would be appreciated.

**Comment by twaik** [comment]
Termux:X11 is constantly changes. Multi-language translation will bring unneeded complication and will force me to translate all new GUI elements as soon as they going to be implemented too all available (supported?) languages.

**Comment by twaik** [comment]
@AlphaBs @hansm629 can you please test latest CI artifact of this PR?

**Pull request closed without merging**
