### PR TITLE
fix `add ic_settings` icon to drawable

### PR DESCRIPTION
**Pull request by ask9027**
Fix : Settings icon not display in shortcut.

### CODE REVIEW

**Comment by twaik** [comment]
Is it final? Can I merge it when check finishes?

**Comment by ask9027** [comment]
> Is it final? Can I merge it when check finishes?

i tested apk also , now its showing properly.

Screenshot_2023-03-03-17-28-52-100-edit_com miui home

**Comment by twaik** [comment]
Did you test it with dark theme?

**Comment by ask9027** [comment]
> Did you test it with dark theme?
It is showing like this
Screenshot_2023-03-03-17-31-18-672-edit_com miui home

**Comment by twaik** [comment]
Can you please make it fit to theme? Black on light theme and white on dark theme?

**Comment by ask9027** [comment]
> Can you please make it fit to theme? Black on light theme and white on dark theme?

Okay i will try.

**Comment by twaik** [comment]
Can you please show how it looks like in different themes?

**Comment by ask9027** [comment]
> Can you please show how it looks like in different themes?

not completed till

**Comment by ask9027** [comment]
Closing untill completed

**Pull request closed without merging**
