### PR TITLE
major t:wayland improvements

### PR DESCRIPTION
**Pull request by ghost**
merging the pr once everything is good

all existing issues and pull requests will be transferred

### CODE REVIEW

**Comment by twaik** [comment]
> Yes... Please do it👍👍

That is a bad idea. T::X11 is called so because Xorg is the only possible client.

**Comment by WMCB-Tech** [comment]
> > Yes... Please do it👍👍
> 
> That is a bad idea. T::X11 is called so because Xorg is the only possible client.

@twaik maybe you're right, perhaps none of the Termux applications was compiled with wayland support

**Comment by twaik** [comment]
I know I am right. T::X11's architecture was built to be the minimal possible server that can handle Xwayland connection. As simple as it can be. And this server used a few tricks to handle Android behaviour.

**Comment by WMCB-Tech** [comment]
maybe... what do you think @suhan-paradkar?

**Comment by suhan-paradkar** [comment]
Yes... But we may need to ask @Grimler91 to change the repo name also... Among others...

**Comment by Grimler91** [comment]
Back to termux-x11 it is then!

**Comment by GrpeApple** [comment]
All is not changed in https://github.com/termux/termux-x11/search?q=wayland ?

**Comment by twaik** [comment]
@GrpeApple Most of search results are parts of dependencies, no need to change them.

**Pull request merged**
