### PR TITLE
Added a setting to force hiding the software keyboard at launch

### PR DESCRIPTION
**Pull request by polkaulfield**
It's useful to have the ability to disable the software keyboard. Also having my USB keyboard connected made the IME pop-up anyways.

### CODE REVIEW

**Comment by twaik** [comment]
I think you are late...

**Comment by twaik** [comment]
I pushed my commit 8 minutes ago :)

**Comment by polkaulfield** [comment]
We were looking into the same issue at once then xD. Gonna try your patch asap.

**Comment by twaik** [comment]
Can you please try to write some gui preference for resolution? Something that will let user choose between resolution presets (like 5:4 / 16:10 or something else), scale (0.1x to 2x) or exact resolution? I am not skilled enough in gui.

**Comment by twaik** [comment]
So what do you think?

**Comment by polkaulfield** [comment]
Added a couple menu options, just the gui. If you want i can try to implement the logic too.

**Comment by twaik** [comment]
No need to. All the code related to EGL and GLES is deprecated and will be removed. I will post the code soon.

**Comment by polkaulfield** [comment]
#214 I added the menus here

**Pull request closed without merging**
