### PR TITLE
option to adjust display height for EK bar

### PR DESCRIPTION
**Pull request by knyipab**
A minimalist implemention of #605

Tested on my samsung fold 5, and no flickering seen. 

Depending on your preference, if needed, it could be added in description "may cause flickering for some devices" to prevent user from opening issues on github.

### CODE REVIEW

**Comment by RalfWerner** [comment]
@knyipab You did a fantastic job! With this version, the behavior of version **1.02.04** is partially restored. However, the `opacityEKBar` option is missing here. In some cases it would useful.
image

The implementation of the keys into [symbols](https://github.com/termux/termux-x11/assets/45426380/22093757-657a-4649-bcd8-69c31156551c) has been incomplete (**red**) since version **1.03.00**. Here a synchronized script for the EK is used in both apps. If you could correct that, it would be almost perfect for the EK. I would prefer the exclusive effect of `hideEKOnVolDown` = **true**.

I edit [Xclients](https://github.com/termux/termux-x11/assets/45426380/333595c3-d890-49ef-997f-b8e4f7686918) who use Direct mode as `touchMode`, where the use of several fingers is the typical case. With every movement of more than two fingers downwards (in X11-App), the EK is toggled on/off. If that would not be done at **true**, this problem would also be solved.

**Comment by RalfWerner** [comment]
@knyipab I wanted to thank you and contribute a few ideas. Unfortunately, the commit (above) was deleted by `termux`. Do you have a channel where this is not done?

**Comment by knyipab** [comment]
I just opened the issues function of [my fork](https://github.com/knyipab/termux-x11) and you may try.

**Comment by twaik** [comment]
> Recalculating size of EK bar and screen surface was used in older versions but it was removed because it caused flickering of screen and there is no fix for this.

https://github.com/termux/termux-x11/assets/9674930/acd756b4-119c-4dcd-9c89-e637ebb4085f

**Pull request merged**
