### PR TITLE
add transformCapturedPointer summary

### PR DESCRIPTION
**Pull request by knyipab**

### CODE REVIEW

**Comment by knyipab** [comment]
Screenshot_20240704_233956_TermuxX11~2

**Comment by twaik** [comment]
It does not seem like it is the most optimal solution.

**Comment by knyipab** [comment]
Didn't take much time, and feel free to not accept and close it.

**Comment by twaik** [comment]
Sorry, it was wrong to do that after you PRed the changes, but 9e422b7bf44e30188f94ba9653cad3360406513d seems to be more effective.

**Pull request closed without merging**
