### PR TITLE
Fix xshmfence

### PR DESCRIPTION
**Pull request by xMeM**
These changes allow Mesa Turnip DRI3 to work without patches.

### CODE REVIEW

**Comment by twaik** [comment]
LGTM. By the way, can you please take a look at the reason why vkcube does not work with dri3+swrast?

**Comment by twaik** [comment]
And one more question. Is https://github.com/xMeM/termux-packages/tree/dev/wrapper ready? Issues are disabled in your fork.

**Comment by twaik** [comment]
Correct, it fixes vkcube with working dri3 and does not seem to brake mesa so I'll merge it.

**Comment by twaik** [comment]
What about vulkan wrapper branch? Is it ready? Probably it is time to file a pull request to termux org repo.

**Comment by xMeM** [comment]
> What about vulkan wrapper branch? Is it ready? Probably it is time to file a pull request to termux org repo.

Ok, I'll open a pull request tomorrow.

**Comment by twaik** [comment]
So this PR makes https://github.com/termux/termux-packages/blob/master/packages/mesa-vulkan-icd-freedreno-dri3/wsi-termux-x11.patch not needed, right?

**Comment by twaik** [comment]
I thought we need to mmap file descriptor we pass there with some offset we get from the `image->base.offsets[0]`. Or it always equals `0`?

**Comment by xMeM** [comment]
> So this PR makes https://github.com/termux/termux-packages/blob/master/packages/mesa-vulkan-icd-freedreno-dri3/wsi-termux-x11.patch not needed, right?

Yes, `mesa-vulkan-icd-freedreno` should work now.

**Comment by xMeM** [comment]
> I thought we need to mmap file descriptor we pass there with some offset we get from the `image->base.offsets[0]`. Or it always equals `0`?

It seems that only YUV formats have offsets, since those formats have multiple planes.

**Comment by Maxython** [comment]
@xMeM, after your patch in termux-x11, mesa-glibc stopped working (all drivers). I already tried to rebuild mesa-glibc without `wsi-termux-x11-v3.patch`, but it did not fix the situation.

**Comment by xMeM** [comment]
https://github.com/termux/termux-packages/blob/187b1de5bc32613574bf43ca22102ab4014c512e/packages/libxshmfence/build.sh#L10
@Maxython Try rebuild `libxshmfence` with the `--disable-futex` option.

**Comment by Maxython** [comment]
@xMeM, I rebuilt `libxshmfence-glibc` with futex disabled. It fixed the usual programs, like `glmark2` or `glxgears`, but `vkcube` and other programs on vulkan still show a black screen (i.e. the problem is not fixed). In addition, I suspect that the new termux-x11 began to show less fps, but perhaps this is already a problem in `mesa-glibc`.

And also, could you look at the [`mesa-glibc`](https://github.com/termux-pacman/glibc-packages/tree/main/gpkg/mesa) package and tell me what needs to be done so that it can work normally with the new termux-x11 (if necessary). Just looking at your PR https://github.com/termux/termux-packages/pull/22500, I think that `mesa-glibc` also needs reconfiguration.

**Comment by xMeM** [comment]
@Maxython libxshmfence fallback to pthread shared mutex after futex is disabled, but glibc cannot share mutex with bionic.
If you can't make xshmfence work, you will have to remove the xshmfence call in mesa.

**Comment by twaik** [comment]
I mean for using it only inside xshmfence lib.

**Comment by twaik** [comment]
It is weird, it looks like pthread uses futex internally (__NR_futex syscall).

**Comment by hansm629** [comment]
@xMeM 
The `mesa Turnip (mesa-vulkan-icd-freedreno)` distributed in the **Termux main-repo** works fine without the `DRI3 patch`.

However, I build and tested `mesa Turnip` in the **PRoot-Distro Debian environment** without applying the `DRI3 patch`, and both `vkcube` and `vkmark` freezing and did not work.

The build process is as follows, but is there something I may have missed or done incorrectly?

https://github.com/user-attachments/assets/0c3eda09-1ccd-46ed-ac97-7915d354a9a5

```
~$ BUILD_PREFIX=~/Desktop
~$ MESA_PREFIX=${BUILD_PREFIX}/mesa-mesa-24.3.1
~$ wget --continue --directory-prefix ${BUILD_PREFIX} https://gitlab.freedesktop.org/mesa/mesa/-/archive/mesa-24.3.1/mesa-mesa-24.3.1.tar.gz
~$ tar -xf ${BUILD_PREFIX}/*.tar.gz --directory ${BUILD_PREFIX}

~$ MESA_VER=$(cat ${MESA_PREFIX}/VERSION)
~$ DATE=$(date +"%F" | sed 's/-//g')
~$ MESA_64=${BUILD_PREFIX}/mesa-vulkan-kgsl_${MESA_VER}-${DATE}_arm64

~$ echo "\
[binaries]
c = 'arm-linux-gnueabihf-gcc'
cpp = 'arm-linux-gnueabihf-g++'
ar = 'arm-linux-gnueabihf-ar'
strip = 'arm-linux-gnueabihf-strip'
pkgconfig = 'arm-linux-gnueabihf-pkg-config'

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'aarch64'
endian = 'little'
" > ${MESA_PREFIX}/arm.txt

~$ sudo meson build64/ --prefix /usr --libdir lib/aarch64-linux-gnu/ -D platforms=x11 -D gallium-drivers=freedreno -D vulkan-drivers=freedreno -D freedreno-kmds=msm,kgsl -D buildtype=release -D glx=disabled -D egl=disabled -D gles1=disabled -D gles2=disabled -D gallium-xa=disabled -D opengl=false -D b_lto=true -D b_ndebug=true -D cpp_rtti=false -D gbm=disabled -D llvm=disabled -D shared-llvm=disabled -D xmlconfig=disabled
~$ sudo meson compile -C build64/
~$ sudo meson install -C build64/ --destdir ${MESA_64}

~$ cd ${BUILD_PREFIX}
~$ sudo apt remove -y mesa-vulkan-drivers:arm64
~$ sudo apt download mesa-vulkan-drivers:arm64
~$ sudo dpkg-deb -e mesa-vulkan-drivers_*_arm64.deb ${MESA_64}/DEBIAN/
~$ sudo sed -ie "3s/.*/Version: ${MESA_VER}-${DATE}/g" ${MESA_64}/DEBIAN/control
~$ sudo rm mesa-vulkan-drivers_*_arm64.deb
~$ sudo rm ${MESA_64}/DEBIAN/md5sums ${MESA_64}/DEBIAN/triggers
~$ sudo rm -rf ${MESA_64}/usr/share/drirc.d
~$ sudo dpkg-deb --build --root-owner-group ${MESA_64}
```

**Comment by xMeM** [comment]
@hansm629 For glibc build, it is still necessary to apply the DRI3 patch.

**Comment by Maxython** [comment]
Frankly speaking, as a developer of glibc packages in Termux, I started to doubt whether these changes are right. Because the new termux-x11 does not simplify the compilation of the `mesa-glibc` package, but also limits the functionality of other packages. This is not good.

**Comment by xMeM** [comment]
@Maxython Just keep the DRI3 patch for mesa-glibc, no changes to other packages are needed.

**Pull request merged**
