### PR TITLE
Forced fullscreen (hides android status bar)

### PR DESCRIPTION
**Pull request by Dr4kzor**
First I would like to say that I am new to the git pull request method. I was not sure how to do this so here I am describing a full list of changes needed to make the App remove the annoying status bar from top of the screen.

Signed-off-by: gradle-update-robot <gradle-update-robot@regolo.cc>

In Android 12 it is not easy to remove the top status bar, as a results we lose a nice portion of the screen when using the phone horizontaly.

As a way to fix this edit the file located in app\src\main\res\values\styles.xml
Added on all themes:  &lt;item name=&quot;android:windowFullscreen&quot;&gt;true&lt;/item&gt;

&lt;resources&gt;
    &lt;!-- Base application theme. --&gt;
    &lt;style name=&quot;AppTheme&quot; parent=&quot;Theme.AppCompat.Light.NoActionBar&quot;&gt;
            &lt;!-- Customize your theme here. --&gt;
            &lt;item name=&quot;android:windowFullscreen&quot;&gt;true&lt;/item&gt;
            &lt;!-- Fullscreen was forced on line above --&gt;
            &lt;item name=&quot;colorPrimary&quot;&gt;@color/colorPrimary&lt;/item&gt;
            &lt;item name=&quot;colorPrimaryDark&quot;&gt;@color/colorPrimaryDark&lt;/item&gt;
            &lt;item name=&quot;colorAccent&quot;&gt;@color/colorAccent&lt;/item&gt;
            &lt;item name=&quot;android:windowTranslucentStatus&quot;&gt;true&lt;/item&gt;
            &lt;item name=&quot;android:windowTranslucentNavigation&quot;&gt;true&lt;/item&gt;
            &lt;item name=&quot;android:fitsSystemWindows&quot;&gt;true&lt;/item&gt;
    &lt;/style&gt;
    &lt;style name=&quot;NoActionBar&quot; parent=&quot;Theme.AppCompat.DayNight.NoActionBar&quot;&gt;
            &lt;item name=&quot;android:windowFullscreen&quot;&gt;true&lt;/item&gt;
            &lt;!-- Fullscreen was forced on line above --&gt;
            &lt;item name=&quot;android:windowActionBar&quot;&gt;false&lt;/item&gt;
            &lt;item name=&quot;android:windowNoTitle&quot;&gt;true&lt;/item&gt;
            &lt;item name=&quot;android:windowTranslucentStatus&quot;&gt;true&lt;/item&gt;
            &lt;item name=&quot;android:windowTranslucentNavigation&quot;&gt;true&lt;/item&gt;
            &lt;item name=&quot;android:fitsSystemWindows&quot;&gt;true&lt;/item&gt;
    &lt;/style&gt;
    &lt;!-- For use w/ external displays to be able to use entire display surface area --&gt;
    &lt;style name=&quot;FullScreen.ExternalDisplay&quot; parent=&quot;@style/Theme.AppCompat.DayNight.NoActionBar&quot;&gt;
            &lt;item name=&quot;android:windowNoTitle&quot;&gt;true&lt;/item&gt;
            &lt;item name=&quot;android:windowActionBar&quot;&gt;false&lt;/item&gt;
            &lt;item name=&quot;android:windowFullscreen&quot;&gt;true&lt;/item&gt;
            &lt;item name=&quot;android:windowContentOverlay&quot;&gt;@null&lt;/item&gt;
    &lt;/style&gt;
&lt;/resources&gt;

A full file with patches below.

[styles.zip](https://github.com/termux/termux-x11/files/10213229/styles.zip)

I tested this on my phone and it did the job =)

### CODE REVIEW

**Comment by kulturguda** [comment]
your build does not work for me on Android (OxygenOS) 13, status, navigation and camera bars appear

**Comment by kulturguda** [comment]
your build does not work for me on Android (OxygenOS) 13, camera, status and navigation bars are still visible
termux-x11

**Comment by kulturguda** [comment]
Your build does not work for me on Android (OxygenOS) 12 and 13 too. Camera, status and navigation bars are still visible.
termux-x11

**Comment by twaik** [comment]
Only gradle files are changed in this PR.

**Pull request closed without merging**
