### PR TITLE
add Chinese strings.xml

### PR DESCRIPTION
**Pull request by liuzhongyi2**

### CODE REVIEW

**Comment by twaik** [comment]
@licy183 @2096779623 can you please check if translations are correct?

**Comment by 2096779623** [comment]
> @licy183 @2096779623 can you please check if translations are correct?

Looks like it was machine translated, which I don't think is very good.

**Comment by twaik** [comment]
OK, so I am closing this.

**Comment by liuzhongyi2** [comment]
https://github.com/user-attachments/assets/74ea1b99-7501-4b7e-b2bf-096bc358a2f6

Use AI to translate one by one.

**Comment by twaik** [comment]
AI is not a magic tool which can help you with anything. Its answers must be checked with real people who really knows what they do.

**Pull request closed without merging**
